[versions]
androidGradlePlugin = "9.0.1"
kotlin = "2.3.10"
ksp = "2.3.6"
hilt = "2.59.2"
kotlinxCoroutines = "1.10.2"
dependencyGuard = "0.5.0"
versionCatalogUpdate = "1.0.1"

androidxAppCompat = "1.7.1"
androidxActivity = "1.12.4"
androidxConstraintLayout = "2.2.1"
androidxDatastore = "1.2.0"
androidxLifecycle = "2.10.0"
androidxPreference = "1.2.1"
androidxWebkit = "1.15.0"
material = "1.13.0"
okhttp = "5.3.2"
touchicon = "0.9.11"
coil = "3.3.0"

ktlint = "1.8.0"

# for release

[libraries]
# classPath
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

kotlinMetadataJvm = { group = "org.jetbrains.kotlin", name = "kotlin-metadata-jvm", version.ref = "kotlin" }
kotlinxCoroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }

androidxAppCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidxActivity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
androidxConstraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintLayout" }
androidxDatastorePreferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastore" }
androidxLifecycleViewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidxPreference = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidxPreference" }
androidxWebkit = { group = "androidx.webkit", name = "webkit", version.ref = "androidxWebkit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
hiltAndroid = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hiltAndroidCompiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt"}
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
coil = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil" }
coilNetworkOkHttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
touchicon = { group = "net.mm2d.touchicon", name = "touchicon", version.ref = "touchicon" }
touchiconOkhttp = { group = "net.mm2d.touchicon", name = "touchicon-http-okhttp", version.ref = "touchicon" }

# debug
okhttpLoggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

ktlint = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint" }

# for release

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "dagger.hilt.android.plugin", version.ref = "hilt" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }

# for release

[bundles]

# for release
